import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <style jsx>{`
        .helo {
          color: red;
        }
      `}</style>
      <Head>
        <title>Hunting Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className={styles.mainNav}>
          <ul>
            <Link href="/">
              <li>Home</li>
            </Link>
            <Link href="/about">
              <li>About</li>
            </Link>
            <Link href="/blog">
              <li>Blog</li>
            </Link>
            <Link href="/contact">
              <li>Contact</li>
            </Link>
          </ul>
        </nav>

        <h1 className={`${styles.center} ${styles.mainHeading}`}>
          Welcome to the Hunting Code
        </h1>
        <span className="helo">Hello</span>
      </main>
    </>
  );
}
